spring:
  application:
    name:
      cloud-file-storage

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8080
  servlet:
    context-path: /api
#
#    data:
#      redis:
#        host: ${REDIS_HOST}
#        port: ${REDIS_PORT}